id = "tort"
name = "TORT Grammar"
description = "TORT grammar support"
version = "0.0.1"
schema_version = 1
authors = ["Maksim Tomkavich <quendimax@gmail.com>"]
repository = "https://github.com/quendimax/zed-tort"

[grammars.tort]
repository = "https://github.com/quendimax/tree-sitter-tort"
commit = "b0009c2264870c3e4f796405edd88c05d8297cb1"
